# Site settings
name                : "Juan Pablo Conejero y Herrera"
title               : "Juan Pablo's personal website"
title_separator     : "-"
url                 : "https://jpconher.github.io"

# Google Analytics
google_analytics: G-C485CSRLQ2

# Plugins
plugins: 
  - jekyll-seo-tag
  
# SEO plugin
author: Juan Pablo Conejero y Herrera
image: https://avatars.githubusercontent.com/u/34621340?s=400&u=9e2097bb3ca0f59528cea8377ebe0c52a36763b8&v=4
description: "Whelcome to my personal website! I am a data scientist currently working as a credit risk modeller."
twitter:
  username: jpconher
  card: summary
social:
  - https://twitter.com/jpconher
  - https://www.linkedin.com/in/juanpabloconejero
  - https://github.com/jpconher
