name: "Juan Pablo's personal website"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Google Analytics
google_analytics: G-C485CSRLQ2

url: "https://jpconher.github.io"
baseurl: ""

plugins: 
  - jekyll-seo-tag
  
# SEO plugin
author: Juan Pablo Conejero y Herrera
image: https://avatars.githubusercontent.com/u/34621340?s=400&u=2cda0182c62a7bd08287ffc12b8b3d817baef1e1&v=4
description: "Welcome to my personal website! I am a second year MSc in Statistics student at KU Leuven. Previously, research assistant at Banco de Espana and Bachelor in Economics at uc3m."
twitter:
  username: jpconher
  card: summary
social:
  - https://twitter.com/jpconher
  - https://www.linkedin.com/in/juanpabloconejero
  - https://github.com/jpconher
